### ISSUE TITLE
Threat

### ISSUE THREAD

**Issue by WyrdoKward** [WyrdoKward/Project-Cards-and-Dices#4]
##TODO

- [x] Fix slider color.Lerp
- [x] Fix paragraphe sur les SO dans l'issue
- [x] Reporter les éléments de l'issue dans une doc technique

## Général
Pas forcément un "monstre" mais peut représenter une menace + abstraite (météo, maladie, malédiction...).
A son propre timer, qui déclenche une action à la fin (Combat, Consommation d'une ressource, blessure d'un follower, spawn d'une autre menace...).
A la fin de son timer, peut disparaître après avoir causé son méfait, ou bien réinitialiser le timer et recommencer jusqu'à ce que la menace soit gérée.

## Neutralisation d'une menace
Un follower doit snapper sur la carte menace.
Ceci va déclencher, après un temps défini, un combat/test (?) qui aura pour issue : 
* réussite : neutralisation de la menace
* échec : conséquence négative propre à cette menace sur le follower ou autre

## Attributs pour le Scriptable Object : 
* threatTime : Temps imparti avant que la menace fasse effet
* isLoop : true si le timer doit recommencer tant qu'elle n'est pas neutralisée
* dices : les dés pour son test

## Où coder les méthodes Success() et Failure() propre à chaque Threat ?
Le SO contient un membre 'Actions' qui est une référence à un 'décorateur' propre à cette carte là.
Quand on créé le SO dans Unity, on lui attache le script xxxActions correspondant.
Le xxxActions implémente les interfaces nécessaires pour lui donner ses comportements.

Exemple : 
* IOutcomes définit Success() et Failure()
* ThiefActions  implémente IOutcomes et donc Success() et Failure() spécifiques à la carte Thief
* ThiefSO.Actions référence ThiefActions 
* La Card Thief.cs accède donc aux méthodes ainsi : `cardSO.Actions.Success()`

On peut mettre ces 'décorateurs' dans 
/Sources/Entities/Interfaces/IOutcomes.cs et
/Sources/Entities/Threats/Actions/ThiefAction.cs
\+ peut être renommer 'Entities' en 'Cards' ?

## Exemple à implémenter pour la vertical slice (Peut être implémenté sans la mécanique du test dans un premier temps)
**Thief** : consomme une ressource aléatoire à la fin du timer. Si il n'y a plus de ressource, il disparaît.

On Snap Follower : 
* Success : Destruction du Thief (on peut faire une v1 sans test)
* Failure : Blesse le follower (Nécessite la mécanique des blessures). On peut faire un v1 sans conséquences sur l'échec.

**Comment by WyrdoKward** [comment]
Slider Color : https://www.youtube.com/watch?v=djpQVauAeDQ
- sliderTimer.Backgound.Color
- sliderTimer.FillArea.Fill.Color

Dans Unity :
+ Remove les sourceImage ?
+ Slider.Transition est bien à none au lieu de Color Tint
+ Interactable = false
